export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "../globals.css"

export default function Layout({ children }) {
  return (
    <body>
      {children}
    </body>
  )
}
